[package]
name = "lotus"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["napi4"] }
napi-derive = "2"
winit = { version = "0.30" }
rustls = { version = "0.23", features = ["aws_lc_rs"] }
webrender = "0.68"
euclid = "0.22"
servo_url = { path = "servo/components/url", package = "servo_url" }
servo = { path = "servo/components/servo", package = "libservo" }

# Cross-platform dependencies
dpi = "0.1"
crossbeam-channel = "0.5"
url = "2.5"
env_logger = "0.11.8"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
rmp-serde = "1.3.1"
byteorder = "1.5.0"
uuid = { version = "1.20.0", features = ["v4"] }
tiny_http = "0.12.0"
urlencoding = "2.1.3"
once_cell = "1.19"
dirs = "5.0"
mime_guess = "2.0.5"
http = "1.4.0"
window-vibrancy = "0.5"
dark-light = "1.0"

# Linux-only dependencies
[target.'cfg(target_os = "linux")'.dependencies]
winit = { version = "0.30", features = ["x11", "wayland"] }
glutin = "0.32"
glutin-winit = "0.5"
raw-window-handle = "0.6"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
